import { PlanRequest, Provider } from "./types";

let mockCallCount = 0;

function shouldReturnInvalidFirst() {
  const enabled = (process.env.KAIR_MOCK_INVALID_FIRST || "").trim() === "1";
  return enabled && mockCallCount === 0;
}

function buildMockPlanJson(request: PlanRequest) {
  return JSON.stringify({
    version: "kair.plan.v1",
    title: `Mock plan for ${request.contractId}`,
    steps: [
      {
        id: "step_prepare",
        title: "Prepare",
        description: `Analyze intent: ${request.intent}`,
      },
      {
        id: "step_apply",
        title: "Apply",
        description: "Produce implementation changes and capture evidence.",
        depends_on: ["step_prepare"],
      },
    ],
    notes: ["Generated by deterministic mock provider"],
  });
}

export const mockProvider: Provider = {
  name: "mock",
  isInstalled() {
    return true;
  },
  requireApiKey() {
    return "";
  },
  async planJson(request: PlanRequest) {
    if (shouldReturnInvalidFirst()) {
      mockCallCount += 1;
      return "{bad json";
    }
    mockCallCount += 1;
    return buildMockPlanJson(request);
  },
};
